name: PR Sanity Check

on: 
  branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packages
        run: |
          npm install


      - name: Test check
        run: |
          npm run test